[build]
publish = "dist/static"
command = "npm run deploy-netlify"
functions = "dist/functions/netlify"

  [build.environment]
  NETLIFY_FUNCTION_ENV = "production"

[[redirects]]
from = "/dynamic/:id"
to = "/.netlify/functions/nextApp"
status = 200

[[redirects]]
from = "/folder/:folder/:id"
to = "/.netlify/functions/nextApp"
status = 200

[[redirects]]
from = "/path/*"
to = "/.netlify/functions/nextApp"
status = 200

[[redirects]]
from = "/ssg-dynamic/:id"
to = "/.netlify/functions/nextApp"
status = 200

[[redirects]]
from = "/ssr"
to = "/.netlify/functions/nextApp"
status = 200

[[redirects]]
from = "/static-dynamic/:id"
to = "/static-dynamic/[id].html"
status = 200
