name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node.js
        uses: actions/setup-node@v1.1.0
      - name: Install dependencies
        run: yarn
      - name: Deploy firebase project
        run: yarn deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
